---
name: compose                         # name of the asset (version would be upended once the asset is generated. Ex: for name unpacker and version 0.1.0, the end artifact would be unpacker_0_1_0)
tempath: test/
path: testing                         # path which unpackker has to pick for its operations while packing, it defaults to working directory
assetpath: path/to/asset              # path to assert dir which has to be packed.
assetversion: "0.1.1"                 # version of the asset that would be packed.
environment: "production"             # name of environment in which the asset has to be packed.
ignore:                               # list of files to be ignore while packing asset.
  - "path/to/exemptfile1"
  - "path/to/exemptfile2"
assetmetadata:                        # metadata to be assigned to the asset.
  unpackkerpacked: true
cleancache: true                      # if cleancache is enabled the traces which were created while packing asset would be cleared.
#configpath: ~/vue/sampleapp/dist
backend:
  cloud: "gcp"                        # name of the cloud as preferred backend if not specified defaults to fs, available options are (fs, gcp, aws, azure).
  bucket: bucket_name                 # name of root bucket.
  folder: past/to/folder              # path of the folders under root bucket if any.
  credspath: path/to/credentials_file # credentails.json incase of gcp
  credstype: "file"                   # credstype is not required field, if not specified it sets to default, available options are (file, default).